import type { CSSProperties } from "react";

/** Style objects for RepoList - use with className from RepoList.module.css (same names) */
export const repoListStyles = {
  root: {
    width: "100%",
    minHeight: "100%",
    padding: 0,
    boxSizing: "border-box",
  } as CSSProperties,
  rootList: {
    width: "100%",
  } as CSSProperties,
  statusBar: {
    padding: "10px 14px",
    marginBottom: "16px",
    borderRadius: "8px",
    fontSize: "13px",
  } as CSSProperties,
  statusBarSuccess: {
    background: "rgba(34, 197, 94, 0.12)",
    color: "#22c55e",
  } as CSSProperties,
  statusBarError: {
    background: "rgba(239, 68, 68, 0.12)",
    color: "#ef4444",
  } as CSSProperties,
  statusBarInfo: {
    background: "rgba(59, 130, 246, 0.1)",
    color: "#3b82f6",
  } as CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: "16px",
    marginBottom: "20px",
  } as CSSProperties,
  headerTitle: {
    margin: 0,
    fontSize: "20px",
    fontWeight: 700,
    color: "#fff",
  } as CSSProperties,
  headerCount: {
    margin: "4px 0 0",
    fontSize: "14px",
    color: "#737373",
  } as CSSProperties,
  filterRow: {
    display: "flex",
    gap: "8px",
  } as CSSProperties,
  select: {
    padding: "8px 12px",
    borderRadius: "8px",
    border: "1px solid #333",
    background: "#1a1a1a",
    color: "#e5e5e5",
    fontSize: "14px",
    cursor: "pointer",
  } as CSSProperties,
  repoList: {
    listStyle: "none",
    padding: 0,
    margin: 0,
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  } as CSSProperties,
  repoCard: {
    padding: "20px",
    background: "#171717",
    borderRadius: "10px",
    border: "1px solid #262626",
    cursor: "pointer",
  } as CSSProperties,
  repoCardSelected: {
    background: "#1f1f1f",
    border: "1px solid #404040",
  } as CSSProperties,
  repoCardHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "12px",
    marginBottom: "8px",
  } as CSSProperties,
  repoName: {
    fontWeight: 600,
    color: "#fff",
    fontSize: "16px",
  } as CSSProperties,
  badge: {
    flexShrink: 0,
    padding: "2px 8px",
    borderRadius: "6px",
    fontSize: "12px",
    fontWeight: 500,
  } as CSSProperties,
  badgePublic: {
    background: "rgba(34, 197, 94, 0.2)",
    color: "#22c55e",
  } as CSSProperties,
  badgePrivate: {
    background: "rgba(249, 115, 22, 0.2)",
    color: "#fb923c",
  } as CSSProperties,
  repoDescription: {
    margin: "0 0 12px",
    fontSize: "14px",
    color: "#a3a3a3",
    lineHeight: 1.4,
  } as CSSProperties,
  repoMeta: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    flexWrap: "wrap",
    fontSize: "13px",
    color: "#737373",
    marginBottom: "16px",
  } as CSSProperties,
  metaItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
  } as CSSProperties,
  metaItemSmall: {
    display: "inline-flex",
    alignItems: "center",
    gap: "4px",
  } as CSSProperties,
  langDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
  } as CSSProperties,
  actionRow: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
    marginTop: "16px",
  } as CSSProperties,
  btnOpenCode: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "8px 14px",
    borderRadius: "8px",
    border: "none",
    background: "#ffced7",
    color: "#000",
    fontSize: "13px",
    fontWeight: 500,
    cursor: "pointer",
  } as CSSProperties,
  btnOpenCodeLoading: {
    background: "#374151",
    cursor: "not-allowed",
  } as CSSProperties,
  btnOpenCodeDisabled: {
    opacity: 0.5,
  } as CSSProperties,
  btnSecondary: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "8px 14px",
    borderRadius: "8px",
    border: "none",
    background: "#262626",
    color: "#e5e5e5",
    fontSize: "13px",
    cursor: "pointer",
  } as CSSProperties,
  btnIconOnly: {
    padding: "8px 14px",
    borderRadius: "8px",
    border: "none",
    background: "#262626",
    color: "#e5e5e5",
    fontSize: "13px",
    cursor: "pointer",
  } as CSSProperties,
  modalOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  } as CSSProperties,
  modalContent: {
    background: "#1e1e1e",
    padding: "24px",
    borderRadius: "12px",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.4)",
    maxWidth: "420px",
    width: "90%",
    border: "1px solid #333",
  } as CSSProperties,
  modalTitle: {
    margin: "0 0 12px",
    color: "#e0e0e0",
  } as CSSProperties,
  modalSubtitle: {
    margin: "0 0 8px",
    color: "#aaa",
    fontSize: "14px",
  } as CSSProperties,
  modalCode: {
    display: "block",
    padding: "8px 12px",
    marginBottom: "16px",
    background: "#2d2d2d",
    borderRadius: "6px",
    fontSize: "13px",
    color: "#9cdcfe",
    overflow: "auto",
  } as CSSProperties,
  modalInput: {
    width: "100%",
    boxSizing: "border-box",
    padding: "10px 12px",
    marginBottom: "12px",
    border: "1px solid #444",
    borderRadius: "8px",
    background: "#2d2d2d",
    color: "#e0e0e0",
    fontSize: "14px",
    outline: "none",
  } as CSSProperties,
  modalTextarea: {
    width: "100%",
    boxSizing: "border-box",
    padding: "10px 12px",
    marginBottom: "16px",
    border: "1px solid #444",
    borderRadius: "8px",
    background: "#2d2d2d",
    color: "#e0e0e0",
    fontSize: "14px",
    minHeight: "80px",
    resize: "vertical",
    outline: "none",
  } as CSSProperties,
  modalActions: {
    display: "flex",
    gap: "8px",
    justifyContent: "flex-end",
  } as CSSProperties,
  btnCancel: {
    padding: "8px 16px",
    border: "1px solid #555",
    borderRadius: "6px",
    background: "#333",
    color: "#e0e0e0",
    cursor: "pointer",
  } as CSSProperties,
  btnSend: {
    padding: "8px 16px",
    border: "none",
    borderRadius: "6px",
    background: "#0d6efd",
    color: "#fff",
    cursor: "pointer",
  } as CSSProperties,
  codeViewRow: {
    display: "flex",
    height: "calc(100vh - 120px)",
    width: "100%",
    position: "relative",
    gap: "16px",
  } as CSSProperties,
  backLink: {
    position: "absolute",
    top: "18px",
    left: "12px",
    zIndex: 10,
    color: "#a3a3a3",
    fontSize: "14px",
    cursor: "pointer",
  } as CSSProperties,
  fileTreeWrap: {
    width: "280px",
    minWidth: "240px",
    flexShrink: 0,
    paddingTop: "48px",
    background: "#252526",
    borderRadius: "8px",
    overflow: "hidden",
  } as CSSProperties,
  editorWrap: {
    flex: 1,
    minWidth: 0,
    padding: "20px",
    overflow: "auto",
    background: "#1a1a1a",
    borderRadius: "8px",
  } as CSSProperties,
};
